"""initial schema

Revision ID: b7a65349143b
Revises: 
Create Date: 2026-07-30 22:15:10.166849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b7a65349143b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scans',
    sa.Column('keyword', sa.String(length=255), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('result_limit', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('total_businesses', sa.Integer(), nullable=False),
    sa.Column('completed_count', sa.Integer(), nullable=False),
    sa.Column('failed_count', sa.Integer(), nullable=False),
    sa.Column('current_business', sa.String(length=255), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('rerun_of_id', sa.Uuid(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('result_limit BETWEEN 1 AND 500', name=op.f('ck_scans__result_limit_range')),
    sa.ForeignKeyConstraint(['rerun_of_id'], ['scans.id'], name=op.f('fk_scans__rerun_of_id'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scans'))
    )
    with op.batch_alter_table('scans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scans__status'), ['status'], unique=False)
        batch_op.create_index('ix_scans__status_created', ['status', 'created_at'], unique=False)

    op.create_table('businesses',
    sa.Column('scan_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('website_url', sa.Text(), nullable=True),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('final_url', sa.Text(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=128), nullable=True),
    sa.Column('country_code', sa.String(length=2), nullable=True),
    sa.Column('category', sa.String(length=128), nullable=True),
    sa.Column('source_provider', sa.String(length=32), nullable=False),
    sa.Column('source_external_id', sa.String(length=255), nullable=True),
    sa.Column('source_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('failure_reason', sa.String(length=32), nullable=True),
    sa.Column('failure_detail', sa.Text(), nullable=True),
    sa.Column('primary_email', sa.String(length=320), nullable=True),
    sa.Column('primary_phone', sa.String(length=32), nullable=True),
    sa.Column('contacts', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('technologies', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('artifacts', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('crawled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('analyzed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], name=op.f('fk_businesses__scan_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_businesses')),
    sa.UniqueConstraint('scan_id', 'domain', name='scan_domain')
    )
    with op.batch_alter_table('businesses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_businesses__domain'), ['domain'], unique=False)
        batch_op.create_index('ix_businesses__scan_status', ['scan_id', 'status'], unique=False)

    op.create_table('jobs',
    sa.Column('scan_id', sa.Uuid(), nullable=True),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('priority', sa.SmallInteger(), nullable=False),
    sa.Column('attempts', sa.SmallInteger(), nullable=False),
    sa.Column('max_attempts', sa.SmallInteger(), nullable=False),
    sa.Column('run_after', sa.DateTime(timezone=True), nullable=False),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('locked_by', sa.String(length=64), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], name=op.f('fk_jobs__scan_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_jobs'))
    )
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.create_index('ix_jobs__claimable', ['status', 'priority', 'run_after'], unique=False)
        batch_op.create_index('ix_jobs__scan', ['scan_id', 'status'], unique=False)

    op.create_table('business_scores',
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.Column('lead_score', sa.SmallInteger(), nullable=False),
    sa.Column('website_score', sa.SmallInteger(), nullable=False),
    sa.Column('security_score', sa.SmallInteger(), nullable=False),
    sa.Column('opportunity_score', sa.SmallInteger(), nullable=False),
    sa.Column('breakdowns', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('lead_score BETWEEN 0 AND 100', name=op.f('ck_business_scores__lead_range')),
    sa.CheckConstraint('opportunity_score BETWEEN 0 AND 100', name=op.f('ck_business_scores__opportunity_range')),
    sa.CheckConstraint('security_score BETWEEN 0 AND 100', name=op.f('ck_business_scores__security_range')),
    sa.CheckConstraint('website_score BETWEEN 0 AND 100', name=op.f('ck_business_scores__website_range')),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], name=op.f('fk_business_scores__business_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('business_id', name=op.f('pk_business_scores'))
    )
    with op.batch_alter_table('business_scores', schema=None) as batch_op:
        batch_op.create_index('ix_business_scores__opportunity', ['opportunity_score'], unique=False)

    op.create_table('findings',
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.Column('check_id', sa.String(length=48), nullable=False),
    sa.Column('plugin_id', sa.String(length=32), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('severity', sa.String(length=12), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('evidence', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('remediation', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], name=op.f('fk_findings__business_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_findings')),
    sa.UniqueConstraint('business_id', 'check_id', name='business_check')
    )
    with op.batch_alter_table('findings', schema=None) as batch_op:
        batch_op.create_index('ix_findings__business_severity', ['business_id', 'severity', 'status'], unique=False)

    op.create_table('opportunities',
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.Column('rule_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('category', sa.String(length=24), nullable=False),
    sa.Column('urgency', sa.String(length=12), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('description_ai', sa.Text(), nullable=True),
    sa.Column('pitch_angle', sa.Text(), nullable=False),
    sa.Column('evidence', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('triggered_by', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], name=op.f('fk_opportunities__business_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_opportunities')),
    sa.UniqueConstraint('business_id', 'rule_id', name='business_rule')
    )
    with op.batch_alter_table('opportunities', schema=None) as batch_op:
        batch_op.create_index('ix_opportunities__business_urgency', ['business_id', 'urgency'], unique=False)

    op.create_table('reports',
    sa.Column('scan_id', sa.Uuid(), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=True),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=64), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], name=op.f('fk_reports__business_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], name=op.f('fk_reports__scan_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reports'))
    )
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.create_index('ix_reports__scan_kind', ['scan_id', 'kind'], unique=False)

    op.create_table('site_snapshots',
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('render_mode', sa.String(length=16), nullable=False),
    sa.Column('final_url', sa.Text(), nullable=True),
    sa.Column('http_status', sa.SmallInteger(), nullable=True),
    sa.Column('failure_reason', sa.String(length=32), nullable=True),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('page_count', sa.SmallInteger(), nullable=False),
    sa.Column('total_bytes', sa.Integer(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], name=op.f('fk_site_snapshots__business_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_site_snapshots')),
    sa.UniqueConstraint('business_id', name=op.f('uq_site_snapshots__business_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('site_snapshots')
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_index('ix_reports__scan_kind')

    op.drop_table('reports')
    with op.batch_alter_table('opportunities', schema=None) as batch_op:
        batch_op.drop_index('ix_opportunities__business_urgency')

    op.drop_table('opportunities')
    with op.batch_alter_table('findings', schema=None) as batch_op:
        batch_op.drop_index('ix_findings__business_severity')

    op.drop_table('findings')
    with op.batch_alter_table('business_scores', schema=None) as batch_op:
        batch_op.drop_index('ix_business_scores__opportunity')

    op.drop_table('business_scores')
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index('ix_jobs__scan')
        batch_op.drop_index('ix_jobs__claimable')

    op.drop_table('jobs')
    with op.batch_alter_table('businesses', schema=None) as batch_op:
        batch_op.drop_index('ix_businesses__scan_status')
        batch_op.drop_index(batch_op.f('ix_businesses__domain'))

    op.drop_table('businesses')
    with op.batch_alter_table('scans', schema=None) as batch_op:
        batch_op.drop_index('ix_scans__status_created')
        batch_op.drop_index(batch_op.f('ix_scans__status'))

    op.drop_table('scans')
    # ### end Alembic commands ###
